// Re-exports all types and constants from shared.ts for convenience
export {
  type Stage,
  type View,
  type Booking,
  type BookingSort,
  type BookingFilter,
  type CrewRecord,
  type GearDocument,
  type GearRecord,
  type AttendanceRecord,
  type AttendanceStatus,
  type EmployeeAllocation,
  type DepartmentDashboardConfig,
  type DepartmentDashboardMetric,
  type DepartmentDashboardWidget,
  type WorkflowChecklistItem,
  stages,
  stageShort,
  initialBookings,
  persistedBookingIds,
  departmentList,
  legacyCrews,
  crews,
  attendanceRoster,
  gears,
  CLIENT_DOCUMENT_CATEGORIES,
  initialUploadDocuments,
  PARALLEL_WORKSTREAMS,
  persistedBookingIdForUi,
  uiBookingIdForPersisted,
  allocationMatchesCrew,
  initials,
  statusTone,
  formatUploadSpeed,
  formatUploadEta,
  canAccessWorkspaceView,
  DEPARTMENTS,
  DEPARTMENT_LABEL_TO_CODE,
  roleLabel,
  canAccessProvisionedDepartmentDashboard,
  DEPARTMENT_DASHBOARD_METRICS,
  DEPARTMENT_DASHBOARD_WIDGETS,
  defaultWorkflowChecklist,
  normalizeDepartmentDashboardConfig,
  findEmployeeBookingConflicts,
  toggleEmployeeBookingAllocation,
  ATTENDANCE_CREW_ROSTER,
  CREW_ASSIGNMENT_ROSTER,
  ATTENDANCE_STATUSES,
  attendanceCompletion,
  attendanceRosterKey,
  computeMonthlyAttendanceSummary,
  dateKey,
  defaultAttendanceRecord,
  formatAttendanceDate,
  historicalAttendanceRecord,
  shiftDate,
  summarizeAttendance,
  updateAttendance,
} from "./shared";
